include:
- ./func/*
kind: ArchiveUploadSpec
name: func-XL6z

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: term-sign-fn-2ccafe66-a131-4439-9eaa-8f968546c674
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: term-sign-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-XL6z
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-08-23T14:14:04Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: term-sign-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: term-sign-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.terms_sign
    packageref:
      name: term-sign-fn-2ccafe66-a131-4439-9eaa-8f968546c674
      namespace: default
  requestsPerPod: 1
  resources: {}
