include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-VmG1

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: term-sign-fn-fd3368cd-2410-4278-a6b8-d7a883e5e460
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-VmG1
  environment:
    name: term-sign-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-11-09T22:19:47Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: term-sign-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: term-sign-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: term-sign-fn-fd3368cd-2410-4278-a6b8-d7a883e5e460
      namespace: default
  requestsPerPod: 10000
  resources: {}
