apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: term-sign-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: term-sign-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /term/sign
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /term/sign
